#
###################################
# Site wide configuration
####################################
#
title: H1L021 - Infosec Blog
email: hilo21@protonmail.com
description: Blue is Sexy.
baseurl: ""
keywords: ["blog", "jekyll"]

plugins: [jekyll-paginate]
paginate_path: "/page:num/"
paginate: 5

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Warsaw
markdown:          kramdown
highlighter:       rouge


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: KALLARK
  avatar: garou.png
  job: "Chubby Security Defender"
  bio: "A guy with transverse infosec skills, decided to land on Exploit development soil."
  email: housam.hajoui@gmail.com
  disqus-shortname:
  twitter: H1L021
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: H1L021
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: hamzaouadia
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: 
  telegram: #username
